compile:
	npx hardhat compile

deploy:
	npx hardhat run ignition/modules/deploy.ts --network amoy

verify:
	npx hardhat verify --network amoy 0xF70d9b5b175Ab7Ae683500C7b3bA329b9DF97E13 604800 "0xF5E93e4eEDbb1235B0FB200fd77068Cb9938eF4f"