compile:
	npx hardhat compile

deploy:
	npx hardhat run ignition/modules/deploy.ts --network amoy

verify:
	npx hardhat verify --network amoy 0xf6b1146Ac6472eEcBa9ADC30C05104f1c0Ee2998 604800 "0xF5E93e4eEDbb1235B0FB200fd77068Cb9938eF4f"