compile:
	npx hardhat compile

deploy:
	npx hardhat run ignition/modules/deploy.ts --network amoy

verify:
	npx hardhat verify --network amoy 0x48f181d1C5a629ECB424D675A17C5006417568c1 604800 "0xF5E93e4eEDbb1235B0FB200fd77068Cb9938eF4f"